// features/customer/services/inventoryApi.js
export {
  fetchItems,
  fetchItemById,
  fetchPromotions,
  testBackendConnection,
  createItem,
  updateItem,
  deleteItem,
  createPromotion,
  updatePromotion,
  deletePromotion,
  fetchInventorySettings,
  saveInventorySettings,
} from '../../../shared/services/inventoryApi.js';

// Booking functions:
export {
  bookFitting,
  getUserBookings,
  createDirectBooking,
  getUserDirectBookings,
  checkDirectBookingAvailability,
  getAllFittingBookings,
  getAllDirectBookings,
  updateFittingBookingStatus,
  updateDirectBookingStatus,
  checkFittingAvailability,
  getAvailableTimeSlots,
  completeFittingWithoutLease,
  rescheduleFitting,
  markLeaseStarted,
  returnLease,
  extendLease,
  getUnavailableDates,
  getBookedFittingSlots,
  getOccupiedDirectDates,
  cancelFittingBooking,    
  cancelDirectBooking,     
} from '../../../shared/services/bookingApi.js';